import Foundation
import RealmSwift

class ChallengeService {
    
    var allChallenges = [Challenge]()
    
    init() {
        
        
        allChallenges.append(Challenge(value: ["name" : "Zweepslag","challengeDescription" : "De speler moet met een slagbeweging van een handdoek, vastgemaakt aan de vloer, een pingpongbal in een wasmand krijgen.", "requirements" : "1 handdoek, 20 pingpongballetjes, 1 wasmand, stevige tape", "instructions" : "1) Het einde van de handdoek wordt aan de grond vastgemaakt met stevige tape. De wasmand wordt 5 meter verderop geplaatst.\n2) Als de tijd begint, mag de speler een ingpongbal op een willekeurige plek van de handdoek leggen. De speler moet de handdoek met 2 handen zodanig bewegen, dat het balletje in de wasmand terecht komt.\n3) De deelnemer mag slechts 1 pingpongbal tegelijkertijd op de handdoek leggen.\n4) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden 1 pingpongbal in de wasmand krijgen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Over De Kop","challengeDescription" : "De speler moet een halfvolle fles water rechtop, op een tafel gooien.", "requirements" : "10 dezelfde plastic flessen, voor de helft gevuld met water, Lijn om de afstand te markeren, Tafel","instructions" : "1) Trek een lijn op 1,5 meter van de tafel. \n2) Als de tijd begint, moet de speler een fles met water met 1 hand op een tafel gooien zodanig dat deze rechtop op de tafel blijft staan. \n3) De speler heeft 10 pogingen om uiteindelijk 1 fles rechtop op de tafel te laten landen. \n 4)Om de opdracht met succes te volbrengen, moet er binnen 60 seconden 1 fles rechtop op de tafel blijven staan."]))
        
        allChallenges.append(Challenge(value: ["name" : "Lepeltje Lepeltje","challengeDescription" : "Sla op een lepel zodanig dat een tweede lepel in een glas wordt gekatapulteerd.", "requirements" : "Minimum 10 lepels, 5 glazen","instructions" : "1) Zet 5 dezelfde glazen op een rij. \n2) Als de tijd begint, mag de speler de lepels op de tafel leggen en erop slaan om ze in het glas te katapulteren. \n3) De lepel moet in één beweging in het glas belanden. De speler mag slechts 1 lepel raken in zijn poging de andere lepel in het glas te laten belanden. \n4) Om deze opdracht met succes te volbrengen, moet de speler in elk van de 5 glazen 1 lepel krijgen. De lepels moeten op de bodem belanden en op de bodem blijven tot de 60 seconden verstreken zijn."]))
        
        allChallenges.append(Challenge(value: ["name" : "Snoepreisje","challengeDescription" : "De speler moet met een rietje in de mond een snoepje transporteren van een schaal naar 4 andere rietjes die rechtop zijn vastgemaakt aan een tafel.", "requirements" : "Schaal met gekleurde snoepjes (kleine gekleurde bolletjes), 5 buigzame rietjes, 2 tafels","instructions" : "1) Bevestig 4 buigzame rietjes verticaal op de tafel. Op een afstand van 2 meter staat de tweede tafel met een schaal snoepjes en 1 buigzaam rietje. \n2) Als de tijd begint, mag de speler met alleen de mond en het rietje een snoepje uit de schaal zuigen om deze naar 1 van de verticale rietjes te transporteren en hierop te laten balanceren. \n3) Als een snoepje valt, telt dit niet meer mee.            \n4) Om de opdracht met succes te volbrengen, moet er binnen 60 seconden op alle 4 de verticale rietjes 1 snoepje liggen. De snoepjes moeten 3 seconden blijven liggen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Door het oog van de naald","challengeDescription" : "Gebruik 1 hand om een draad door het oog van 10 naalden te rijgen.", "requirements" : "Draad 10 naalden (elk van verschillende grootte) - isomoplaat","instructions" : "1) Alle naalden worden van groot naar klein met de scherpe kant naar beneden in een stevig oppervlak (isomoplaat) vastgezet.            \n2) Voor het spel begint, mag de speler kiezen welke hand hij zal gebruiken.         \n3) Als de tijd begint, mag de speler het garen in de mond stoppen of buigen zoveel als nodig. \n4) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden de draad door alle 10 de naalden rijgen."]))
        
        allChallenges.append(Challenge(value: ["name" : "In schoenvlucht","challengeDescription" : "Gebruik je voet om een schoen op tafel te gooien.", "requirements" : "12 schoenen, 1 tafel","instructions" : "1) Zet 12 schoenen neer op 3 meter van een tafel. \n2) Als de tijd begint, moet de speler zijn voet in een schoen zetten en deze met zijn voet op de tafel werpen. \n3) De speler mag niet dichter bij de tafel gaan staan of de handen gebruiken. \n4) Een schoen mag half op de tafel terecht komen, mits deze 3 seconden op de tafel blijft liggen met de zool op tafel. \n 5) Om deze opdracht met succes te volbrengen moet de speler binnen 60 seconden een schoen op de tafel krijgen die 3 seconden blijft liggen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Stapelgek","challengeDescription" : "De speler moet een stapel maken van 36 plastic bekers in de vorm van een driehoek. Als dit volbracht is, moeten de bekers terug naar 1 enkele stapel gebracht worden.", "requirements" : " 36 plastic bekers, Tafel","instructions" : "1) Als de tijd begint, moet de speler de bekers in een piramide stapelen. In totaal ontstaan er 8 rijen. \n2) Als de driehoek compleet is, met 1 beker bovenop, 2 daaronder en zo verder, dient de speler de bekers terug te brengen naar 1 enkele stapel. \n3) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden een complete piramide bouwen, waarbij alle bekers worden gebruikt om hierna alle bekers opnieuw tot 1 stapel terug te brengen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Wet van Newton","challengeDescription" : "Houd 3 ballonnen 1 minuut lang in de lucht.", "requirements" : "3 ballonnen (opgeblazen)","instructions" : "1) Als de tijd begint, laat de speler 3 ballonnen los in de lucht. \n2) De speler mag de ballonnen niet vasthouden, op het lichaam laten rusten of op de grond laten vallen. Anders is het spel afgelopen. \n3) Om de opdracht met succes te volbrengen, moet de speler de ballonnen 60 seconden lang in de lucht houden."]))
        
        allChallenges.append(Challenge(value: ["name" : "Driesprong","challengeDescription" : "De speler moet 3 pingpongballen in een kom gooien door ze eerst op 3 borden te laten stuiteren.", "requirements" : "3 borden (ongeveer 26 cm diameter), Meerdere pingpongballen, 1 kom","instructions" : "1) Zet 3 borden in een rechte lijn met de randen 2,5 cm van elkaar. Plaats de viskom 25 cm vanaf de rand van het laatste bord.            \n2) Als de tijd begint, mag de speler de pingpongballen via de borden in de viskom laten stuiteren. \n3) De pingpongballen moeten alle borden minimum 1 keer raken. \n4) Elke pingpongbal die de grond raakt, telt niet. \n5) De speler mag alleen met 1 gekozen hand gooien. \n6) Om de opdracht met succes te volbrengen, moeten er, binnen 60 seconden, 3 pingpongballen in de viskom beland zijn."]))
        
        allChallenges.append(Challenge(value: ["name" : "Loopneus","challengeDescription" : "De speler moet 5 watten bolletjes van de ene schaal naar de andere verplaatsen met de neus die is ingesmeerd met vaseline.", "requirements" : "Minimum 5 watten bolletjes, Vaseline, 2 schalen, Tafel","instructions" : "1) Zet de schalen 3,5 meter uit elkaar met de watjes in 1 van de schalen. \n2) Als de tijd begint, mag de speler zijn neus in de vaseline doppen. \n3) Met de vaseline op de neus worden de watjes opgepakt, dit zonder de handen te gebruiken. \n4) Als de speler meerdere watjes per keer transporteert, tellen geen van deze als ze in de schaal terecht komen. \n5) De speler moet het watje rechtstreeks van de neus in de schaal deponeren, zonder in contact te komen met een ander lichaamsdeel of object. \n6) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden 5 watjes transporteren van de eerste schaal naar de tweede."]))
        
        allChallenges.append(Challenge(value: ["name" : "Blikvanger","challengeDescription" : "De speler moet door middel van lege blikjes en papieren borden een omgekeerde piramide bouwen.", "requirements" : "15 lege blikjes, 4 kartonnen borden, Tafel","instructions" : "1) Het spel begint met 15 blikjes aan de ene kant van de tafel en de papieren borden aan de andere kant. \n2) De speler begint met 1 blikje onderaan met daarop een papieren bord. Op dat bord komen 2 blikjes en zo verder tot het bouwwerk 5 verdiepingen telt. \n3) Om deze opdracht met succes te volbrengen, moet de speler binnen 60 seconden 5 lagen van blikjes met daartussen een papieren bord stapelen waarbij de laatste laag 5 blikjes bevat."]))
        
        allChallenges.append(Challenge(value: ["name" : "Moer toren","challengeDescription" : "De speler moet een toren bouwen door 10 grote moeren van een Chinees stokje te laten glijden.", "requirements" : "1 Chinees stokje, 10 metalen moeren ,Tafel","instructions" : "1) Zet alle 10 de metalen moeren op het Chinese stokje en leg deze op de tafel. \n2) Als de tijd begint mag de speler het stokje optillen en de moeren 1 voor 1 in een hoge toren op elkaar stapelen. \n3) De speler mag ten allen tijde maar 1 hand gebruiken. De speler mag de andere hand ook niet gebruiken om de eerste hand te ondersteunen. \n4) De speler mag de moeren met geen enkel lichaamsdeel aanraken. \n5) Het stokje en de moeren mogen alleen de tafel raken gedurende het plaatsen van de eerste moer, hierna is het spel direct over als het stokje of een andere moer de tafel raakt. \n6) Om deze opdracht met succes te volbrengen moet er binnen 60 seconden een stapel van 10 moeren met een stokje gebouwd worden. De moertoren moet 3 seconden blijven staan."]))
        
        allChallenges.append(Challenge(value: ["name" : "Waterballon","challengeDescription" : "De speler moet een ballon in een vuilnisbak manoeuvreren door gebruik te maken van een plantenspuit.", "requirements" : "Lijn op 3,5 meter, 3 opgeblazen ballonnen in een bak, 1 plantenspuit gevuld met water, 1 vuilnisbak (150 liter)","instructions" : "1) Plaats de vuilnisbak op 3,5 meter van de lijn en zet de bak met ballonnen achter de lijn. \n2) Als de tijd begint, mag de speler achter de lijn de ballon in de lucht gooien en proberen de ballon naar de vuilnisbak te leiden met alleen het gebruik van de plantenspuit. \n3) De ballon mag noch de grond, noch de plantenspuit zelf, noch het lichaam van de speler aanraken. \n4) De speler mag een oude ballon hergebruiken of een nieuwe ballon pakken bij de nieuwe poging. \n5) Om de opdracht met succes te volbrengen, moet binnen 60 seconden 1 ballon in de vuilnisbak beland zijn."]))
        
        allChallenges.append(Challenge(value: ["name" : "De langste adem","challengeDescription" : "De speler moet een ballon opblazen en laten leeglopen om zo 15 plastic bekers van een tafel te blazen.", "requirements" : "Minimum 1 ballon, 15 plastic bekers, Tafel","instructions" : "1) Zet 15 plastic bekers in een rij op de tafel. \n2) Als de tijd begint, mag de speler de ballon pakken en hem beginnen op te blazen. \n3) De speler moet aan 1 kant van de tafel blijven en mag uitsluitend met de lucht uit de ballon de bekers van de tafel gooien. (hij mag de ballon wel opnieuw opblazen indien dit nodig is) \n4) Als de speler een beker aanraakt met een deel van het lichaam dan is het spel direct afgelopen. \n5) Om de opdracht met succes te volbrengen, moeten binnen 60 seconden alle plastic bekers van de tafel geblazen worden."]))
        
        allChallenges.append(Challenge(value: ["name" : "Papieren wolkenkrabber","challengeDescription" : "De deelnemer moet een toren bouwen van steekkaarten, waarvan elke laag bestaat uit 2 op voorhand gevouwen kaarten waar een platte kaart op rust.", "requirements" : "30 indexkaarten","instructions" : "1) Vouw 20 indexkaarten horizontaal in het midden van de kaart. \n2) Als de tijd begint, mag de speler beginnen met het bouwen van de toren waarbij elke laag bestaat uit 2 gevouwen kaarten en 1 platte kaart bovenop. \n3) De speler mag tijdens het spel geen vouwen meer maken. \n4) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden een toren bouwen van 10 lagen. De toren moet 3 seconden in zijn geheel blijven staan."]))

        allChallenges.append(Challenge(value: ["name" : "Jenga Domino","challengeDescription" : "De speler moet een domino pad creëren met blokken van het reuze jengaspel die op de korte zijde rechtop staan. De speler duwt de pakken zo omver dat het laatste pak de bel doet rinkelen.", "requirements" : "reuze jengaspel, 1 bel","instructions" : "1) Zet 1 blok rechtop op de korte kant 3 meter van de bel af. \n2) Als de tijd begint, mag de speler 1 blok per keer pakken en plaatsen tussen het eerste pak en de bel. \n3) De speler moet per keer 1 blok dragen en mag de pakken niet gooien of schuiven.        \n4) Als een blok omvalt gedurende het spel dan mag de speler deze oppakken en verder gaan. \n5) Om het domino effect te creëren mag de speler alleen de eerste blok duwen. \n6) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden het domino effect creëren, waarbij 11 blokken papier 1 voor 1 omvallen en de laatste blok de bel doet rinkelen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Olifantenmars","challengeDescription" : "Gooi flessen om met een tennisbal hangende in een panty die over het hoofd getrokken wordt.", "requirements" : "8 volle plastic flessen (50 cl), 1 panty, 1 tennisbal, Lijn op de grond","instructions" : "1) Zet de flessen in 2 rijen, 3 meter uit elkaar, met de lijn tussen de 2 rijen in. \n2) Plaats de bal in de panty en trek de panty over het hoofd. \n3) Als de tijd begint mag de speler het hoofd bewegen richting flessen, maar beide benen moeten altijd aan 1 kant van de lijn blijven. \n4) De speler mag geen andere lichaamsdelen gebruiken om de bal in beweging te krijgen. \n5) Om de opdracht met succes te volbrengen, dient de speler binnen 60 seconden alle 8 flessen omver te gooien."]))
        
        allChallenges.append(Challenge(value: ["name" : "Pasta mania","challengeDescription" : "Gebruik je mond om 6 pasta penne, aan 1 ongekookte spaghetti te rijgen.", "requirements" : "6 rolletjes pasta penne (ongekookt), 1 sliert spaghetti (ongekookt), 1 tafel","instructions" : "1) Voor het spel begint, moet de speler de armen naast zich houden. \n2) Als het spel daadwerkelijk begint, mag de speler even de handen gebruiken om de sliert spaghetti te pakken en in zijn mond te stoppen. \n3) Als de spaghetti in de mond zit, mogen de handen niet meer gebruikt worden. \n4) Als de spaghetti breekt, dan gaat het spel wel verder maar moeten alle stukken penne nog steeds op de spaghetti passen. \n5) De penne mag van de spaghetti afvallen maar blijft alleen in het spel als deze op de tafel valt. \n6) De penne mag de lippen raken maar niet in de mond terecht komen. \n7) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden, met enkel de mond, 6 stukken penne aan de spaghetti zien te rijgen. Hierna dient hij deze nog 3 seconden vast te houden zonder op de tafel te steunen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Communicerende vaten","challengeDescription" : "3 lege blikjes en 3 volle moeten van de ene hand in de andere terechtkomen zonder ze neer te zetten.", "requirements" : "3 lege aluminium blikjes, 3 volle aluminium blikjes, Tafel","instructions" : "1) Stapel de 3 lege blikjes naast de 3 volle blikjes op de tafel. \n2) Als de tijd begint, moet de speler de lege blikjes optillen met 1 hand en de volle blikjes met de andere hand. \n3) Zodra de blikjes opgetild zijn, mogen deze niet meer op de tafel neergezet worden totdat de opdracht geslaagd is. \n4) De blikjes mogen alleen met de handen aangeraakt worden. \n5) Om de opdracht met succes te volbrengen, moeten alle blikjes binnen de 60 seconden van de ene hand naar de andere hand overgeheveld zijn en op de tafel blijven staan."]))
        
        allChallenges.append(Challenge(value: ["name" : "Blikken en Blozen","challengeDescription" : "De speler moet proberen om door middel van het schieten van elastiekjes een driehoekige toren van blikjes volledig om te gooien.", "requirements" : "Rubberen elastieken, 6 lege blikjes, Lijn om afstand te markeren, Smalle tafel", "instructions" : "1) Plaats 6 lege frisdrankblikjes in een driehoekige toren bovenop een tafel. Trek een lijn op 2,50 meter van de tafel. \n2) Als de tijd begint, moet de speler achter de lijn gaan staan en de elastiekjes één voor één naar de toren schieten. \n3) Om de opdracht met succes te volbrengen, moet binnen 60 seconden de hele tafel leeg zijn. Hiervoor mag de speler alleen maar elastiekjes gebruiken."]))
        
        allChallenges.append(Challenge(value: ["name" : "Ken je pen","challengeDescription" : "De speler moet een potlood in een glas stuiteren.", "requirements" : "7 glazen, Minimum 7 ongeslepen potloden met gom","instructions" : "1) Zet 7 glazen op een rij. \n2) Vooraleer hij begint, kiest de speler een hand waarmee hij zal gooien en de andere hand om de potloden vast te houden. De potloden moeten 1 voor 1 in het glas gestuiterd worden. \n3) De potloden moeten via de tafel stuiteren en direct in het glas belanden. \n4) Om de opdracht met succes te volbrengen, moet er binnen 60 seconden in elk van de 7 glazen 1 potlood beland zijn."]))
        
        allChallenges.append(Challenge(value: ["name" : "Bellen blazen","challengeDescription" : "De speler moet een zeepbel blazen en door een hoepel leiden.", "requirements" : "1 hoepel, 1 bellenblazer (dus ook water en afwasmiddel om eventueel te hervullen)","instructions" : "1) Als de tijd begint, mag de speler de bellenblazer pakken en bellen gaan blazen van achter de startlijn. \n2) De speler mag enkel alleen zijn adem als aansporing gebruiken. \n3) De speler mag de hoepel, noch de zeepbel aanraken. \n4) Om de opdracht met succes te volbrengen, moet binnen 60 seconden een intacte zeepbel, geblazen voor de lijn, door de hoepel gaan."]))
        
        allChallenges.append(Challenge(value: ["name" : "Blaaskaak","challengeDescription" : "De speler moet 52 speelkaarten wegblazen terwijl de joker bovenop de glazen fles blijft liggen.", "requirements" : "shit enzo","instructions" : "1) Stapel een pak speelkaarten met de plaatjes naar beneden op elkaar met alleen een joker met het plaatje naar boven. De joker moet onderaan de stapel liggen. \n2) Balanceer dit pak speelkaarten op de mond van een glazen fles. \n3) Als de tijd begint, moet de speler de kaarten wegblazen van de stapel. \n4) De speler mag de kaarten en de fles niet aanraken. \n5) Om de opdracht met succes te volbrengen, moeten binnen 60 seconden alle kaarten weggeblazen worden en moet de joker nog op de mond van de fles blijven liggen. Deze moet hier 3 seconden blijven liggen."]))
        
        allChallenges.append(Challenge(value: ["name" : "Zaklopen","challengeDescription" : "Verplaats 5 papieren zakken, van verschillende hoogtes, met alleen de mond.", "requirements" : "5 glazen flessen, 5 pakken speelkaarten met 52 kaarten en een joker","instructions" : "1) Knip 5 papieren zakken op verschillende hoogtes (30 cm, 25 cm, 20 cm, 15 cm, 10 cm) en zet deze rechtop op de grond. \n2) Als de tijd ingaat, moet de speler met de mond de zakken 1 voor 1, van groot naar klein verplaatsen naar de tafel. \n3) Alleen de voeten mogen de grond raken. \n4) Als de speler met een ander lichaamsdeel dan de voeten de grond raakt bij het pakken van een zak dient deze eerst weer rechtop gezet te worden voordat een nieuwe poging gedaan mag worden. \n5) Om de opdracht met succes te volbrengen moeten alle zakken binnen 60 seconden op de tafel staan."]))
        
        allChallenges.append(Challenge(value: ["name" : "Kleur bekennen","challengeDescription" : "Sorteer 18 gekleurde snoepjes per kleur.", "requirements" : "18 snoepjes 6 van 3 verschillende kleuren (mnm’s), 18 plastic bekers (ondoorzichtig), 3 glazen, 4 tafels", "instructions" : "1) Plaats elk snoepje willekeurig onder een beker in het midden van de tafel. \n2) Plaats elk van de drie glazen op de drie andere tafels, opgesteld rond de centrale tafel. \n3) Als de tijd begint, moet de speler een bekertje optillen, het snoepje nemen en naar het juiste glas brengen. \n4) Als de speler meerdere bekers tegelijkertijd omdraait of meerdere snoepjes tegelijkertijd vast neemt is het spel afgelopen. \n5) De snoepjes moeten per kleur gesorteerd worden. De speler mag kiezen welk glas voor welke kleur bestemd is. \n6) Als de speler een snoepje met de verkeerde kleur in een glas doet, is het spel afgelopen. \n7) Om deze opdracht met succes te volbrengen, moet de speler binnen 60 seconden alle 18 snoepjes, in groepen van 6 van dezelfde kleur in een glas deponeren."]))
        
        allChallenges.append(Challenge(value: ["name" : "Appelboom","challengeDescription" : "Stapel 5 rode appels bovenop elkaar.", "requirements" : "Minimum 5 rode appels, Tafel","instructions" : "1) Als de tijd begint, mag de speler de appels op elkaar stapelen. \n2) De speler mag niets aan de appels veranderen. \n3) Om de opdracht met succes te volbrengen, moet de speler binnen 60 seconden 5 appels op elkaar stapelen zodat deze minstens 3 seconden blijven staan."]))
        
        allChallenges.append(Challenge(value: ["name" : "De rode draad","challengeDescription" : "De speler start met een stapel rode bekers en 1 blauwe beker onderaan. De speler moet de bekers één voor één van boven naar beneden brengen zodat de blauwe beker uiteindelijk weer onderaan belandt.", "requirements" : "39 rode bekers, 1 blauwe beker","instructions" : "1) Maak een stapel van 39 rode bekers met 1 blauwe beker onderaan. \n2) Als de tijd begint, moet de speler de bekers 1 voor 1 pakken en van boven naar beneden brengen.\n3) De speler mag maar één hand gebruiken om een beker te pakken en moet bij iedere nieuwe beker van hand wisselen.\n4) Als er meer dan 1 beker per keer wordt gepakt, dan moeten deze teveel gepakte bekers eerst terug naar boven geplaatst worden voordat de deelnemer verder mag gaan.\n5) De opdracht moet staande uitgevoerd worden.\n6) Om de opdracht met succes te volbrengen, moet de blauwe beker onderaan de stapel belanden nadat deze door de hele stapel is gegaan. De hand moet bij de blauwe beker zijn als de 60 seconden om zijn."]))
        
    }
    
    func getRandomChallenges(amount: Int) -> [Challenge]{
        
        
        return allChallenges.choose(amount)
    
    }
    
    
}

extension Array {
    /// Returns an array containing this sequence shuffled
    var shuffled: Array {
        var elements = self
        return elements.shuffle()
    }
    /// Shuffles this sequence in place
    @discardableResult
    mutating func shuffle() -> Array {
        indices.dropLast().forEach {
            guard case let index = Int(arc4random_uniform(UInt32(count - $0))) + $0, index != $0 else { return }
            swap(&self[$0], &self[index])
        }
        return self
    }
    var chooseOne: Element { return self[Int(arc4random_uniform(UInt32(count)))] }
    func choose(_ n: Int) -> Array { return Array(shuffled.prefix(n)) }
}
